services:
  web:
    image: guestbook:v0.1.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:7
    ports: 
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  redis-data: {}

